In [1]:
import pandas as pd
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [3]:
array = np.array((1,2,3,4,5))
type(array), array

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [4]:
zero_array = np.array(9)
zero_array, zero_array.ndim

(array(9), 0)

In [5]:
one_array = np.array([1,2,3,4,5])
one_array, one_array.ndim

(array([1, 2, 3, 4, 5]), 1)

In [6]:
two_array = np.array([[1,2,3], [4,5,6]])
two_array, two_array.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [7]:
three_array = np.array([[[1,2,3], [4,5,6]], [[11,12,13], [14,15,16]]])
three_array, three_array.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[11, 12, 13],
         [14, 15, 16]]]),
 3)

In [8]:
array = np.array([1,2,3,4,5], ndmin=2)
array, array.ndim

(array([[1, 2, 3, 4, 5]]), 2)

In [9]:
array = np.array([1,2,3,4,5])
array[2], array[2:4], array[2:4:2], array[2:-2]

(np.int64(3), array([3, 4]), array([3]), array([3]))

In [10]:
array[2] + array[3]

np.int64(7)

In [11]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array[1,1], array[1, 1:3]

(np.int64(5), array([5, 6]))

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1, 1, 1], array[1, 1:3]

(np.int64(11), array([5, 6]))

In [13]:
array = np.array([[1,2,3], [4,5,6],[7,8,9]])
array[1, -1]

np.int64(6)

In [14]:
array = np.array([1,2,3,4,5])
array.dtype

dtype('int64')

In [15]:
array = np.array(['a', 'b', 'c'])
array.dtype

dtype('<U1')

In [16]:
array = np.array([1,2,3,4,5], dtype='S')
array.dtype, array.astype(int)

(dtype('S1'), array([1, 2, 3, 4, 5]))

In [17]:
array = np.array([1,2,3,4,5,6])
array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
array = np.array([1,2,3,4,5,6])
carray = array.copy()
varray = array.view()
carray.base, varray.base

(None, array([1, 2, 3, 4, 5, 6]))

In [19]:
array = np.array([1,2,3,4,5,6])
even_array = np.where(array % 2 == 0)
even_array

(array([1, 3, 5]),)