In [1]:
import pandas as pd
import numpy as np

In [2]:
n = np.random.randint(100)
n

53

In [3]:
n = np.random.rand()
n

0.24391833141087127

In [4]:
array = np.random.randint(100, size=(3))
array

array([71, 48, 96], dtype=int32)

In [5]:
array = np.random.randint(100, size=(3,3))
array

array([[82, 80, 42],
       [12, 48, 21],
       [ 1, 17,  2]], dtype=int32)

In [6]:
array = np.random.rand(3)
array

array([0.11755124, 0.25417946, 0.21471843])

In [7]:
array = np.random.rand(3,2)
array

array([[0.97079458, 0.89623554],
       [0.52189222, 0.21584932],
       [0.88958949, 0.64261533]])

In [8]:
c = np.random.choice([1,2,3,4])
c

np.int64(3)

In [9]:
c = np.random.choice([1,2,3,4], size=(2,2))
c

array([[2, 1],
       [4, 3]])

In [10]:
array = np.random.choice([1,3,5,7], p=[0.1,0.2,0.3,0.4], size=(100))
array

array([7, 7, 3, 7, 3, 7, 5, 5, 7, 7, 1, 5, 3, 7, 3, 7, 1, 5, 3, 7, 7, 7,
       5, 7, 7, 3, 5, 3, 7, 1, 5, 7, 5, 5, 7, 5, 1, 5, 5, 5, 7, 5, 3, 7,
       5, 1, 5, 5, 7, 5, 7, 7, 7, 7, 1, 5, 7, 3, 7, 5, 7, 1, 7, 7, 1, 7,
       7, 5, 7, 1, 5, 7, 1, 5, 7, 7, 7, 5, 3, 5, 1, 7, 5, 5, 5, 5, 5, 7,
       5, 7, 3, 3, 1, 5, 5, 3, 1, 5, 5, 7])

In [11]:
arary = np.random.choice([1,3,5,7], p=[0.0, 0.1, 0.3,0.6], size=(2,3))
arary

array([[7, 7, 5],
       [7, 7, 5]])

In [12]:
array = np.random.randint(100, size=(5))
array

array([40, 30, 99, 52, 99], dtype=int32)

In [13]:
np.random.shuffle(array)
array

array([99, 52, 99, 40, 30], dtype=int32)

In [14]:
array = np.random.randint(100, size=(5))
array

array([57, 66, 87, 70, 57], dtype=int32)

In [15]:
new_array = np.random.permutation(array)
array, new_array

(array([57, 66, 87, 70, 57], dtype=int32),
 array([57, 66, 57, 70, 87], dtype=int32))

In [16]:
normal_dist = np.random.normal(size=(3,2))
normal_dist

array([[ 2.04652579,  0.64412977],
       [-1.0980887 ,  0.6176218 ],
       [-0.22378019, -0.15025678]])

In [17]:
normal_dist = np.random.normal(loc=1, scale=2, size=(3,3))
normal_dist

array([[ 0.47736394, -1.97590841,  1.27965376],
       [ 2.58155672,  0.12540369,  1.61989467],
       [ 1.41971624,  1.30859538,  4.8838895 ]])

In [18]:
binomial_dist = np.random.binomial(n=10, p=0.5, size=10)
binomial_dist

array([8, 2, 6, 4, 5, 3, 7, 5, 6, 7], dtype=int32)

In [19]:
poission_dist = np.random.poisson(lam=2, size=10)
poission_dist

array([1, 2, 2, 3, 3, 3, 2, 1, 0, 2], dtype=int32)

In [20]:
uniform_dist = np.random.uniform(size=(20))
uniform_dist

array([0.78049977, 0.81454322, 0.58081615, 0.71773868, 0.5630928 ,
       0.36619493, 0.77253365, 0.29324981, 0.932805  , 0.47208943,
       0.28644107, 0.23388149, 0.71057238, 0.87220829, 0.81707491,
       0.56912089, 0.37043122, 0.83659672, 0.65584493, 0.4342256 ])

In [21]:
logistic_dist = np.random.logistic(loc=1, scale=2, size=(2, 3))
logistic_dist

array([[ 5.31378566,  7.85983411, -2.99167108],
       [-3.69626568,  5.7125554 , -0.27381197]])

In [22]:
multi_dist = np.random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
multi_dist

array([1, 1, 0, 2, 1, 1], dtype=int32)

In [23]:
exp_dist = np.random.exponential(scale=2, size=(2, 3))
exp_dist

array([[ 0.90704632,  0.3457244 ,  0.27761773],
       [ 0.77126276,  0.55468239, 10.08104923]])

In [24]:
chi_dist = np.random.chisquare(df=2, size=(2, 3))
chi_dist

array([[0.5829882 , 1.47493476, 1.03060363],
       [0.96899654, 5.02029987, 1.04012203]])

In [25]:
ray_dist = np.random.rayleigh(scale=2, size=(2, 3))
ray_dist

array([[5.16249607, 6.26867032, 1.50990092],
       [0.92924459, 0.34763853, 2.66180955]])

In [26]:
par_dist = np.random.pareto(a=2, size=(2, 3))
par_dist

array([[0.00901235, 1.05615419, 0.10795106],
       [1.13331453, 4.95765668, 1.69944189]])

In [27]:
zip_dist = np.random.zipf(a=2, size=(2, 3))
zip_dist

array([[ 1,  1, 50],
       [ 2,  1,  4]], dtype=int32)

In [28]:
np.array([1,1.2, True, 'ada'])

array(['1', '1.2', 'True', 'ada'], dtype='<U32')