In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
# Load Churn_Modelling.csv dataset
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
# Devide dataset into independant and dependant variables
X = df.iloc[:,3:13]
y = df.iloc[:, 13]

In [4]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [5]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [6]:
# Convert categorical clolumn values into binaries called categorical encoding, because neural networks only understand numbers, not text.
geography = pd.get_dummies(X['Geography'], drop_first=True)
gender = pd.get_dummies(X['Gender'], drop_first=True)

In [7]:
geography

Germany  Spain
0       False  False
1       False   True
2       False  False
3       False  False
4       False   True
...       ...    ...
9995    False  False
9996    False  False
9997    False  False
9998     True  False
9999    False  False

[10000 rows x 2 columns]

In [8]:
gender

Male
0     False
1     False
2     False
3     False
4     False
...     ...
9995   True
9996   True
9997  False
9998   True
9999  False

[10000 rows x 1 columns]

In [9]:
X.drop(['Geography', 'Gender'], axis=1, inplace=True)

In [10]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  
0                  1        101348.88  
1                  1        112542.58  
2                  0        113931.57  
3                  0         93826.63  
4                  1         79084.10  
...              ...              ...  
9995               0         96270.64  
9996               1        101699.77  
9997               1         42085.58  
9998               0         92888.52  
9999               0         38190.78  

[10000 rows x 8 columns]

In [11]:
X = pd.concat([X, geography, gender], axis=1)

In [12]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0                  1        101348.88    False  False  False  
1                  1        112542.58    False   True  False  
2                  0        113931.57    False  False  False  
3                  0         93826.63    False  False  False  
4                  1         79084.10    False   True  False  
...              ...              ...      ...    ...    ...  
9995               0         96270.64    False  False   True  
9996               1        101699.77    False  False   True  
9997               1         42085.58    False  False  False  
9998               0         92888.52     True  False   True  
9999               0         38190.78    False  False  False  

[10000 rows x 11 columns]

In [13]:
# Split dataset into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
X_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
7389          667   34       5       0.00              2          1   
9275          427   42       1   75681.52              1          1   
2995          535   29       2  112367.34              1          1   
5316          654   40       5  105683.63              1          1   
356           850   57       8  126776.30              2          1   
...           ...  ...     ...        ...            ...        ...   
9225          594   32       4  120074.97              2          1   
4859          794   22       4  114440.24              1          1   
3264          738   35       5  161274.05              2          1   
9845          590   38       9       0.00              2          1   
2732          623   48       1  108076.33              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
7389               0        163830.64    False   True  False  
9275               1         57098.00     True  False   True  
2995               0        185630.76    False  False  False  
5316               0        173617.09    False   True   True  
356                1        132298.49    False   True  False  
...              ...              ...      ...    ...    ...  
9225               1        162961.79     True  False  False  
4859               1        107753.07    False   True  False  
3264               0        181429.87    False  False   True  
9845               1        148750.16    False   True  False  
2732               0        118855.26     True  False  False  

[8000 rows x 11 columns]

In [15]:
X_test

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9394          597   35       8  131101.04              1          1   
898           523   40       2  102967.41              1          1   
2398          706   42       8   95386.82              1          1   
5906          788   32       4  112079.58              1          0   
2343          706   38       5  163034.82              2          1   
...           ...  ...     ...        ...            ...        ...   
1037          625   24       1       0.00              2          1   
2899          586   35       7       0.00              2          1   
9549          578   36       1  157267.95              2          1   
2740          650   34       4  142393.11              1          1   
6690          573   30       8  127406.50              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
9394               1        192852.67     True  False  False  
898                0        128702.10    False  False  False  
2398               1         75732.25    False   True  False  
5906               0         89368.59    False  False   True  
2343               1        135662.17     True  False   True  
...              ...              ...      ...    ...    ...  
1037               1        180969.55    False  False  False  
2899               0         70760.69    False  False  False  
9549               0        141533.19    False   True   True  
2740               1         11276.48     True  False   True  
6690               0        192950.60     True  False   True  

[2000 rows x 11 columns]

In [16]:
y_train

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

In [17]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [18]:
# Feature scaling, Changing the numerical range of your data without changing the meaning of the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]], shape=(8000, 11))

In [20]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]], shape=(2000, 11))

In [21]:
# Initilize ANN
classifier = Sequential()

In [22]:
# Adding input layer
classifier.add(Dense(units=11, activation='relu'))

In [37]:
# Adding first hidden layer
classifier.add(Dense(units=7, activation='relu'))
classifier.add(Dropout(0.2))

In [24]:
# Adding second hidden layer
classifier.add(Dense(units=6, activation='relu'))

In [25]:
# Adding output layer
classifier.add(Dense(units=1, activation='sigmoid'))

In [26]:
# Adding optimizer and loss function
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
# Early stopping, automatically happens when same results coming
early_stopping = EarlyStopping(
    monitor='val_loss', min_delta=0.0001, patience=20, verbose=1, mode='auto', baseline=None, restore_best_weights=False 
)

In [29]:
model_history = classifier.fit(X_train, y_train, validation_split=0.33, batch_size=10, epochs=100, callbacks=early_stopping)

Epoch 1/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7962 - loss: 0.4855 - val_accuracy: 0.7955 - val_loss: 0.4487
Epoch 2/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7962 - loss: 0.4317 - val_accuracy: 0.7955 - val_loss: 0.4335
Epoch 3/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.7962 - loss: 0.4187 - val_accuracy: 0.7955 - val_loss: 0.4238
Epoch 4/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.8132 - loss: 0.4062 - val_accuracy: 0.8292 - val_loss: 0.4135
Epoch 5/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8343 - loss: 0.3920 - val_accuracy: 0.8391 - val_loss: 0.4005
Epoch 6/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.8451 - loss: 0.3769 - val_accuracy: 0.8387 - val_loss: 0.3896
Epoch 7/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8502 - loss: 0.3652 - val_accuracy: 0.8478 - val_loss: 0.3798
Epoch 8/100
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8546 - loss: 0.3555 - val

In [30]:
# Making predictions and evaluating model
y_pred = classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [32]:
# Make confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1514,   81],
       [ 195,  210]])

In [35]:
# Calculate accuracy
score = accuracy_score(y_pred, y_test)
score

0.862